name: Flask App CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install safety requests

    - name: Dependency check
      run: safety check --full-report

    - name: Start Flask app
      run: |
        python app.py &
        sleep 5

    - name: UI HTTP tests
      run: |
        curl --fail http://127.0.0.1:5000/
        curl --fail "http://127.0.0.1:5000/result?term=test"