name: Flask App CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety

    - name: Run security check
      run: safety check || true

    - name: Start Flask app in background
      run: |
        export FLASK_APP=app.py
        nohup flask run --host=127.0.0.1 --port=5000 &
        sleep 5

    - name: Run basic UI tests
      run: |
        curl --fail http://127.0.0.1:5000/
        curl --fail --get --data-urlencode "term=test" http://127.0.0.1:5000/result